before_script:
       - composer install
       - phpunit

rspec:
  script: "rake spec"
  tags:
    - ruby
    - postgres
  only:
    - branches

# staging:
#   script: "cap deploy stating"
#   type: deploy
#   tags:
#     - capistrano
#     - debian
#   except:
#     - stable
#     - /^deploy-.*$/
